### ISSUE TITLE
Default socket options

### ISSUE THREAD

**Issue by wojtekmach** [elixir-ecto/myxql#46]
Currently, MyXQL defaults to `protocol: :socket` (UNIX domain socket), which should yield better performance than going over tcp.

However, I noticed the default recbuf is much smaller:

```elixir
iex> {:ok, sock} = :gen_tcp.connect('localhost', 3306, [:binary, packet: :raw, active: false])
iex> :inet.getopts(sock, [:buffer, :sndbuf, :recbuf])
{:ok, [buffer: 1460, sndbuf: 146988, recbuf: 408300]}

iex> {:ok, sock} = :gen_tcp.connect({:local, "/tmp/mysql.sock"}, 0, [:binary, packet: :raw, active: false])
iex> :inet.getopts(sock, [:buffer, :sndbuf, :recbuf])
{:ok, [buffer: 1460, sndbuf: 8192, recbuf: 8192]}
```

which yields worse performance on bigger datasets compared to connecting over tcp.

(Btw, we do the same trick as Postgrex & Mariaex when we set internal socket buffer based on sndbuf/recbuf: https://github.com/elixir-ecto/myxql/commit/384b9ba54ebea49996c431fed192a3f083dc38b3)

@josevalim @fishcakez do you have any ideas why domain socket starts with smaller buffers? From what I could read, sndbuf and rebuf set by VM should be a reasonable default. Should we try to bump them anyway? Or default to connecting over TCP like Postgrex and Mariaex does?

**Comment by josevalim** [comment]
I defer my opinion to James. :P

**Comment by fishcakez** [comment]
sndbuf and recbuf default are set by OS defaults, not VM, so it depends on
OS configuration. If you set them the OS may choose different (biggest)
values. I think changing these for Unix sockets may have no impact, :buffer
could be more important as that's the VM buffer for copying from OS buffer.
It depends on how socket recv is done in myxqk. Mariaex and postgrex have
higher :buffer because they used to use active mode with packet type 0,
which would limit bytes sent per message from socket to 1460 by default
value.

**Comment by josevalim** [comment]
What James said.

**Comment by wojtekmach** [comment]
I re-run the numbers and I don't see a significant difference one way or another anymore, so it was a red herring. We'll keep defaulting to unix domain socket for now unless there are any concerns.

**Comment by wojtekmach** [comment]
Btw, currently we always use passive mode for sockets.
