### ISSUE TITLE
Allow port to be a String in the config file

### ISSUE THREAD

**Issue by TheSquad** [elixir-ecto/myxql#85]
A feature that is in mariaex, for those who use `REPLACE_OS_VARS` in the config file, the port is not accepted as String in MyXQL.

I already have a PR ready as soon as I get a go...

**Comment by maartenvanvliet** [comment]
Would it not be better to cast the env var to an integer in your config file instead of deferring that to MyXQL?

**Comment by josevalim** [comment]
As @maartenvanvliet suggested, this should be handled in your config files, instead of pushing this concern downstream. Or use a database URL (if you are using Ecto), which is a string and will be parsed out correctly. Thanks!

**Comment by TheSquad** [comment]
I was suggesting this because mariaex handled it, it would be easier to upgrade to myxql.
Since it is already handled in myxql here : 
`default_port = String.to_integer(System.get_env("MYSQL_TCP_PORT") || "3306")` 
but only when port is not present in the config file, didn't see the harm to cast it one line below

**Comment by wojtekmach** [comment]
@TheSquad I definitely agree easing the path from mariaex to myxql is important. We don't intend to make the change you're suggesting because of the reasons mentioned above, but perhaps we could solve this particular problem by documenting the difference in [`MARIAEX_COMPATIBILITY`](https://github.com/elixir-ecto/myxql/blob/master/MARIAEX_COMPATIBILITY.md)? A PR is appreciated.

**Comment by TheSquad** [comment]
@wojtekmach I also agree that this type of change should not occur at that level, but for those who uses releases, and do not use the exact env name "MYSQL_TCP_PORT" for the port, they will need to do extensive change to upgrade to myxql, probably change their whole deployment process (Our case exactly), in order to allow runtime environment variable replacement.
This might hold back some people to upgrade.

**Comment by wojtekmach** [comment]
I believe the change comes down updating:

```elixir
# config/prod.exs
config :myapp, Myapp.Repo,
  port: "${MYSQL_PORT}",
  ...
```

to:

```elixir
# config/prod.exs
config :myapp, Myapp.Repo,
  port: String.to_integer("${MYSQL_PORT}"),
  ...
```

am I missing something? How are you configuring your repo?

**Comment by TheSquad** [comment]
`port: String.to_integer("${MYSQL_PORT}")` is done at compile time
We use a CI that compile and create a release tar.gz,
This release is deployed, in Testing / Staging / Prod
On each one of them, the DB Port is different.
At compile time, the "${MYSQL_PORT}" is not replaced

**Comment by wojtekmach** [comment]
Yeah, I was just gonna post that was wrong advice, sorry for confusion.

Another thing that you can do is configure your repo at runtime by implementing the [`Ecto.Repo.init/2`](https://hexdocs.pm/ecto/Ecto.Repo.html#c:init/2) like this:

```elixir
def init(_type, config) do
  {:ok, Keyword.put(config, :port, String.to_integer(System.get_env("MYSQL_PORT")))}
end
```

Here's a relevant docs section that José mentioned about using database url: https://hexdocs.pm/ecto/Ecto.Repo.html#module-urls

**Comment by TheSquad** [comment]
Thanks @wojtekmach that workaround gets us to what we need.
Although I think this is kinda hiding the configuration at code level.

Is there a way I could convince you guys to handle the convention `{:system, "VAR"}` tuple ?

**Comment by wojtekmach** [comment]
Yeah, on one hand it’s mixing code with config, but on the other it gives you capabilities that are otherwise not possible with configuration files like reading the db url from Consul etc _when repo starts_.

Sorry, there’s pretty much no way we’ll handle :system tuples. But the good news is Elixir v1.9 releases comes with much better solution which is _runtime_ configuration file and config providers. I’ve written a post about moving hex.pm from distillery (we were using REPLACE_OS_VARS too) that you might find helpful: http://blog.plataformatec.com.br/2019/05/updating-hex-pm-to-use-elixir-releases/

**Comment by TheSquad** [comment]
thanks for your help @wojtekmach, I'll take a look at the post
