### ISSUE TITLE
foreign_key_constraint changeset error

### ISSUE THREAD

**Issue by byronpc** [elixir-ecto/myxql#94]
On the previous driver mysql, a changeset error is being returned when a foreign key constriant is detected...I'm however receiving a raised error here with `%MyXQL.Error{mysql: %{code: 1032}}`. 

Is this properly handled? Or is foreign_key_constraint not working on changesets?

**Comment by josevalim** [comment]
We have integration tests for this feature and the tests work as expected,
so there needs to be a bit more going on here. Can you please do a complete
report on the Ecto SQL project, including the versions and a way to
reproduce the error? Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by josevalim** [comment]
Closing this for now. Let's continue on https://github.com/elixir-ecto/ecto_sql/ with a new report whenever you want. :)

**Comment by wojtekmach** [comment]
The error is `ER_KEY_NOT_FOUND`:

```
$ perror 1032
MySQL error code MY-001032 (ER_KEY_NOT_FOUND): Can't find record in '%-.192s'
```

but we only handle `ER_ROW_IS_REFERENCED_2` and `ER_NO_REFERENCED_ROW_2` (https://github.com/elixir-ecto/ecto_sql/blob/v3.2.2/lib/ecto/adapters/myxql/connection.ex#L53). 

We were not handling that error code on the previous adapter either (https://github.com/elixir-ecto/ecto_sql/blob/v3.1.6/lib/ecto/adapters/mysql/connection.ex#L66) so not sure how this worked for you before.

The fix is easy, we only need to add `ER_KEY_NOT_FOUND` to the list but we need a way to reproduce, if you can please open up an issue on ecto_sql as José mentioned.

**Comment by byronpc** [comment]
I will open there. just gathering up information. aparently it seems even ecto_sql 3 also has the issue.
